import { LogOut, MessageCircle, Plus, Send, UserMinus, UsersRound } from 'lucide-react'
import { useMemo, useState } from 'react'
import type { Chat, ChatMessage, Profile } from '../types'
import { Avatar, EmptyState, Modal } from '../components/UI'
import { ProfilePicker } from '../components/ProfilePicker'

export function ChatsPage({me,profiles,chats,messages,onCreate,onSend,onRead,onLeave,onRemove}:{me:Profile;profiles:Profile[];chats:Chat[];messages:ChatMessage[];onCreate:(title:string,ids:string[])=>Promise<void>;onSend:(chatId:number,body:string)=>Promise<void>;onRead:(chatId:number)=>Promise<void>;onLeave:(chat:Chat)=>Promise<void>;onRemove:(chat:Chat,id:string)=>Promise<void>}){
  const[selectedId,setSelectedId]=useState(chats[0]?.id??null);const[creating,setCreating]=useState(false);const[body,setBody]=useState('')
  const selected=chats.find((chat)=>chat.id===selectedId)??chats[0]
  const rows=useMemo(()=>selected?messages.filter((message)=>message.chat_id===selected.id):[],[messages,selected])
  const unread=(chat:Chat)=>messages.filter((message)=>message.chat_id===chat.id&&message.author_id!==me.id&&(!chat.last_read_at?.[me.id]||message.created_at>chat.last_read_at[me.id]!)).length
  const choose=(chat:Chat)=>{setSelectedId(chat.id);void onRead(chat.id)}
  return <><div className="page-title"><div><span className="eyebrow">Командное общение</span><h1>Чаты</h1><p>Личные и групповые обсуждения с коллегами, руководителем и HR.</p></div><button className="button primary" onClick={()=>setCreating(true)}><Plus/>Новый чат</button></div><section className="card chats-page"><aside className="chat-sidebar"><h3>Сообщения</h3>{chats.map((chat)=><button className={selected?.id===chat.id?'active':''} key={chat.id} onClick={()=>choose(chat)}><span className="chat-avatar"><MessageCircle/></span><span><strong>{chat.title}</strong><small>{chat.participant_ids?.length??0} участников</small></span>{unread(chat)>0&&<b>{unread(chat)}</b>}</button>)}</aside><div className="chat-conversation">{selected?<><header><div><strong>{selected.title}</strong><small>{selected.participant_ids?.map((id)=>profiles.find((p)=>p.id===id)?.full_name).filter(Boolean).join(', ')}</small></div><button className="icon-button danger" title="Выйти из чата" onClick={()=>void onLeave(selected)}><LogOut/></button></header><div className="messages">{rows.map((message)=>{const author=profiles.find((p)=>p.id===message.author_id);return <article className={`message ${message.author_id===me.id?'mine':''}`} key={message.id}><small>{message.author_id===me.id?'Вы':author?.full_name??'Сотрудник'}</small><p>{message.body}</p><time>{new Date(message.created_at).toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'})}</time></article>})}{!rows.length&&<EmptyState icon={<MessageCircle/>} title="Начните разговор" text="Первое сообщение появится здесь."/>}</div><form className="chat-compose" onSubmit={(event)=>{event.preventDefault();if(!body.trim())return;void onSend(selected.id,body.trim()).then(()=>setBody(''))}}><input value={body} onChange={(event)=>setBody(event.target.value)} placeholder="Напишите сообщение…"/><button aria-label="Отправить"><Send/></button></form>{selected.created_by===me.id&&<div className="chat-members">{selected.participant_ids?.filter((id)=>id!==me.id).map((id)=>{const person=profiles.find((p)=>p.id===id);return person?<button key={id} onClick={()=>void onRemove(selected,id)} title="Удалить из чата"><Avatar profile={person} size="sm"/><span>{person.full_name}</span><UserMinus/></button>:null})}</div>}</>:<EmptyState icon={<UsersRound/>} title="Чатов пока нет" text="Создайте личный или групповой чат с коллегами."/>}</div></section>{creating&&<CreateChat profiles={profiles.filter((p)=>p.id!==me.id)} onClose={()=>setCreating(false)} onCreate={async(title,ids)=>{await onCreate(title,ids);setCreating(false)}}/>}</>
}

function CreateChat({profiles,onClose,onCreate}:{profiles:Profile[];onClose:()=>void;onCreate:(title:string,ids:string[])=>Promise<void>}){const[title,setTitle]=useState('');const[selected,setSelected]=useState<string[]>([]);return <Modal title="Новый чат" subtitle="Можно выбрать одного или нескольких сотрудников" onClose={onClose}><form className="form-stack" onSubmit={(event)=>{event.preventDefault();if(selected.length)void onCreate(title||profiles.filter((p)=>selected.includes(p.id)).map((p)=>p.full_name).join(', '),selected)}}><label>Название<input value={title} onChange={(event)=>setTitle(event.target.value)} placeholder="Например, Команда проекта"/></label><fieldset><legend>Участники</legend><ProfilePicker profiles={profiles} selectedIds={selected} onChange={setSelected} multiple/></fieldset><div className="modal-actions"><button type="button" className="button secondary" onClick={onClose}>Отмена</button><button className="button primary" disabled={!selected.length}>Создать чат</button></div></form></Modal>}
