import { Download, Eye, File, FilePlus2, Pencil, Trash2, UploadCloud } from 'lucide-react'
import { useState } from 'react'
import type { DocumentItem, Profile } from '../types'
import { AccessEditor, type ShareDraft } from '../components/AccessEditor'
import { Badge, EmptyState, Modal } from '../components/UI'

const sizeLabel=(bytes:number)=>bytes>1048576?`${(bytes/1048576).toFixed(1)} МБ`:`${Math.max(1,Math.round(bytes/1024))} КБ`

export function DocumentsPage({me,profiles,items,onUpload,onUpdate,onHide,onDelete,onOpen}:{me:Profile;profiles:Profile[];items:DocumentItem[];onUpload:(file:File,title:string,share:ShareDraft)=>Promise<void>;onUpdate:(item:DocumentItem,title:string,share:ShareDraft)=>Promise<void>;onHide:(item:DocumentItem)=>Promise<void>;onDelete:(item:DocumentItem)=>Promise<void>;onOpen:(item:DocumentItem,download?:boolean)=>Promise<void>}){
  const[uploading,setUploading]=useState(false);const[editing,setEditing]=useState<DocumentItem|null>(null);const[deleting,setDeleting]=useState<DocumentItem|null>(null)
  const canManage=(item:DocumentItem)=>item.owner_id===me.id||me.is_head_hr
  return <><div className="page-title"><div><span className="eyebrow">Файлы и материалы</span><h1>Документы</h1><p>Открывайте, скачивайте и делитесь файлами с нужными сотрудниками.</p></div><button className="button primary" onClick={()=>setUploading(true)}><FilePlus2/>Загрузить файл</button></div>
    <section className="material-grid">{items.map((item)=><article className="material-card" key={item.id}><div className="file-symbol"><File/></div><div className="material-copy"><div><Badge tone="purple">{item.file_name.split('.').pop()?.toUpperCase()||'ФАЙЛ'}</Badge><small>{sizeLabel(item.size_bytes)} · {new Date(item.created_at).toLocaleDateString('ru-RU')}</small></div><h3>{item.title}</h3><p>{item.file_name}</p></div><div className="material-actions"><button className="icon-button" title="Открыть" onClick={()=>void onOpen(item)}><Eye/></button><button className="icon-button" title="Скачать" onClick={()=>void onOpen(item,true)}><Download/></button>{canManage(item)&&<button className="icon-button" title="Изменить доступ" onClick={()=>setEditing(item)}><Pencil/></button>}<button className="icon-button danger" title="Удалить" onClick={()=>setDeleting(item)}><Trash2/></button></div></article>)}{!items.length&&<div className="card material-empty"><EmptyState icon={<UploadCloud/>} title="Документов пока нет" text="Загрузите первый файл и выберите, кому он будет доступен."/></div>}</section>
    {uploading&&<DocumentForm profiles={profiles} onClose={()=>setUploading(false)} onSubmit={async(file,title,share)=>{if(!file)return;await onUpload(file,title,share);setUploading(false)}}/>}
    {editing&&<DocumentForm profiles={profiles} item={editing} onClose={()=>setEditing(null)} onSubmit={async(_file,title,share)=>{await onUpdate(editing,title,share);setEditing(null)}}/>}
    {deleting&&<Modal title="Удалить документ?" subtitle={deleting.title} onClose={()=>setDeleting(null)}><p className="modal-explainer">Выберите, где удалить документ. Удаление у всех окончательное.</p><div className="delete-choices"><button className="button secondary" onClick={()=>setDeleting(null)}>Отмена</button><button className="button secondary" onClick={()=>void onHide(deleting).then(()=>setDeleting(null))}>Только у себя</button>{canManage(deleting)&&<button className="button danger-button" onClick={()=>void onDelete(deleting).then(()=>setDeleting(null))}>У всех</button>}</div></Modal>}
  </>
}

function DocumentForm({profiles,item,onClose,onSubmit}:{profiles:Profile[];item?:DocumentItem;onClose:()=>void;onSubmit:(file:File|null,title:string,share:ShareDraft)=>Promise<void>}){const[file,setFile]=useState<File|null>(null);const[title,setTitle]=useState(item?.title??'');const[share,setShare]=useState<ShareDraft>({access_scope:item?.access_scope??'private',department:item?.department??null,recipient_ids:item?.recipient_ids??[]});return <Modal title={item?'Изменить документ':'Загрузить документ'} subtitle="Поддерживаются документы, таблицы, PDF, изображения и другие рабочие файлы" onClose={onClose} wide><form className="form-stack" onSubmit={(e)=>{e.preventDefault();if(item||file)void onSubmit(file,title||file?.name||'',share)}}>{!item&&<label className="upload-zone"><input type="file" onChange={(e)=>{const next=e.target.files?.[0]??null;setFile(next);if(next&&!title)setTitle(next.name)}}/><UploadCloud/><strong>{file?.name??'Выберите файл'}</strong><span>До 50 МБ</span></label>}<label>Название<input value={title} onChange={(e)=>setTitle(e.target.value)} required/></label><AccessEditor profiles={profiles} value={share} onChange={setShare}/><div className="modal-actions"><button type="button" className="button secondary" onClick={onClose}>Отмена</button><button className="button primary">{item?'Сохранить':'Загрузить'}</button></div></form></Modal>}
