import { Download, Eye, File, FilePlus2, Link2, Pencil, Trash2, UploadCloud } from 'lucide-react'
import { useRef, useState } from 'react'
import type { DocumentItem, Profile } from '../types'
import { AccessEditor, type ShareDraft } from '../components/AccessEditor'
import { Badge, EmptyState, Modal } from '../components/UI'

const sizeLabel=(bytes:number)=>bytes>1048576?`${(bytes/1048576).toFixed(1)} МБ`:`${Math.max(1,Math.round(bytes/1024))} КБ`

export function DocumentsPage({me,profiles,items,onUpload,onUpdate,onHide,onDelete,onOpen}:{me:Profile;profiles:Profile[];items:DocumentItem[];onUpload:(file:File,title:string,share:ShareDraft)=>Promise<void>;onUpdate:(item:DocumentItem,title:string,share:ShareDraft)=>Promise<void>;onHide:(item:DocumentItem)=>Promise<void>;onDelete:(item:DocumentItem)=>Promise<void>;onOpen:(item:DocumentItem,download?:boolean)=>Promise<void>}){
  const[uploading,setUploading]=useState(false);const[editing,setEditing]=useState<DocumentItem|null>(null);const[deleting,setDeleting]=useState<DocumentItem|null>(null)
  const canManage=(item:DocumentItem)=>item.owner_id===me.id||me.is_head_hr
  return <><div className="page-title"><div><span className="eyebrow">Файлы и материалы</span><h1>Документы</h1><p>Открывайте, скачивайте и делитесь файлами с нужными сотрудниками.</p></div><button className="button primary" onClick={()=>setUploading(true)}><FilePlus2/>Загрузить файл</button></div>
    <section className="material-grid">{items.map((item)=><article className="material-card" key={item.id}><div className="file-symbol"><File/></div><div className="material-copy"><div><Badge tone="purple">{item.file_name.split('.').pop()?.toUpperCase()||'ФАЙЛ'}</Badge><small>{sizeLabel(item.size_bytes)} · {new Date(item.created_at).toLocaleDateString('ru-RU')}</small></div><h3>{item.title}</h3><p>{item.file_name}</p></div><div className="material-actions"><button className="icon-button" title="Открыть" onClick={()=>void onOpen(item)}><Eye/></button><button className="icon-button" title="Скачать" onClick={()=>void onOpen(item,true)}><Download/></button>{canManage(item)&&<button className="icon-button" title="Изменить доступ" onClick={()=>setEditing(item)}><Pencil/></button>}<button className="icon-button danger" title="Удалить" onClick={()=>setDeleting(item)}><Trash2/></button></div></article>)}{!items.length&&<div className="card material-empty"><EmptyState icon={<UploadCloud/>} title="Документов пока нет" text="Загрузите первый файл и выберите, кому он будет доступен."/></div>}</section>
    {uploading&&<DocumentForm profiles={profiles} onClose={()=>setUploading(false)} onSubmit={async(file,title,share)=>{if(!file)return;await onUpload(file,title,share);setUploading(false)}}/>}
    {editing&&<DocumentForm profiles={profiles} item={editing} onClose={()=>setEditing(null)} onSubmit={async(_file,title,share)=>{await onUpdate(editing,title,share);setEditing(null)}}/>}
    {deleting&&<Modal title="Удалить документ?" subtitle={deleting.title} onClose={()=>setDeleting(null)}><p className="modal-explainer">Выберите, где удалить документ. Удаление у всех окончательное.</p><div className="delete-choices"><button className="button secondary" onClick={()=>setDeleting(null)}>Отмена</button><button className="button secondary" onClick={()=>void onHide(deleting).then(()=>setDeleting(null))}>Только у себя</button>{canManage(deleting)&&<button className="button danger-button" onClick={()=>void onDelete(deleting).then(()=>setDeleting(null))}>У всех</button>}</div></Modal>}
  </>
}

function DocumentForm({profiles,item,onClose,onSubmit}:{profiles:Profile[];item?:DocumentItem;onClose:()=>void;onSubmit:(file:File|null,title:string,share:ShareDraft)=>Promise<void>}){
  const inputRef=useRef<HTMLInputElement>(null);const[source,setSource]=useState<'file'|'link'>('file');const[file,setFile]=useState<File|null>(null);const[url,setUrl]=useState('https://');const[title,setTitle]=useState(item?.title??'');const[share,setShare]=useState<ShareDraft>({access_scope:item?.access_scope??'private',department:item?.department??null,recipient_ids:item?.recipient_ids??[]});const[busy,setBusy]=useState(false);const[error,setError]=useState('')
  const choose=(next:File|null)=>{setError('');if(next&&next.size>52428800){setFile(null);setError('Файл больше 50 МБ. Выберите файл меньшего размера.');return}setFile(next);if(next&&!title)setTitle(next.name)}
  const submit=async()=>{let nextFile=file;if(!item&&source==='link'){let parsed:URL;try{parsed=new URL(url)}catch{setError('Введите корректную ссылку.');return}if(!['http:','https:'].includes(parsed.protocol)){setError('Ссылка должна начинаться с http:// или https://');return}const safeName=(title.trim()||'Ссылка').replace(/[^a-zA-Zа-яА-ЯёЁ0-9._-]/g,'_');nextFile=new globalThis.File([parsed.toString()],`${safeName}.url`,{type:'text/uri-list'})}if(!item&&!nextFile){setError('Сначала выберите файл.');return}setBusy(true);setError('');try{await onSubmit(nextFile,title||nextFile?.name||'',share)}catch(cause){setError(cause instanceof Error?cause.message:'Не удалось добавить документ')}finally{setBusy(false)}}
  const disabled=busy||(!item&&(source==='file'?!file:!title.trim()||!url.trim()||url==='https://'))
  return <Modal title={item?'Изменить документ':'Загрузить документ'} subtitle="Добавьте рабочий файл или ссылку на внешний ресурс" onClose={onClose} wide><form className="form-stack" onSubmit={(e)=>{e.preventDefault();void submit()}}>{!item&&<><div className="document-source-toggle"><button type="button" className={`button small ${source==='file'?'primary':'secondary'}`} onClick={()=>{setSource('file');setError('')}}><UploadCloud/>Файл</button><button type="button" className={`button small ${source==='link'?'primary':'secondary'}`} onClick={()=>{setSource('link');setError('')}}><Link2/>Ссылка</button></div>{source==='file'?<div className={`upload-zone ${file?'has-file':''}`} role="button" tabIndex={0} onClick={()=>inputRef.current?.click()} onKeyDown={(e)=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();inputRef.current?.click()}}} onDragOver={(e)=>e.preventDefault()} onDrop={(e)=>{e.preventDefault();choose(e.dataTransfer.files?.[0]??null)}}><input ref={inputRef} type="file" onChange={(e)=>choose(e.target.files?.[0]??null)}/><UploadCloud/><strong>{file?.name??'Выберите файл или перетащите его сюда'}</strong><span>{file?sizeLabel(file.size):'До 50 МБ · любой рабочий формат'}</span><button type="button" className="button secondary small" onClick={(e)=>{e.stopPropagation();inputRef.current?.click()}}>{file?'Выбрать другой':'Открыть файлы'}</button></div>:<label>Ссылка<input type="url" value={url} onChange={(e)=>setUrl(e.target.value)} placeholder="https://example.com" required/></label>}</>}<label>Название<input value={title} onChange={(e)=>setTitle(e.target.value)} required/></label><AccessEditor profiles={profiles} value={share} onChange={setShare}/>{error&&<div className="form-error" role="alert">{error}</div>}<div className="modal-actions"><button type="button" className="button secondary" onClick={onClose} disabled={busy}>Отмена</button><button className="button primary" disabled={disabled}>{busy?'Загружаем…':item?'Сохранить':source==='link'?'Добавить ссылку':'Загрузить'}</button></div></form></Modal>
}
