import { ExternalLink, Link2, Pencil, Plus, Trash2 } from 'lucide-react'
import { useState } from 'react'
import type { Profile, ResourceLink } from '../types'
import { AccessEditor, type ShareDraft } from '../components/AccessEditor'
import { EmptyState, Modal } from '../components/UI'

export function LinksPage({me,profiles,items,onCreate,onUpdate,onHide,onDelete}:{me:Profile;profiles:Profile[];items:ResourceLink[];onCreate:(values:{title:string;url:string;description:string},share:ShareDraft)=>Promise<void>;onUpdate:(item:ResourceLink,values:{title:string;url:string;description:string},share:ShareDraft)=>Promise<void>;onHide:(item:ResourceLink)=>Promise<void>;onDelete:(item:ResourceLink)=>Promise<void>}){const[editing,setEditing]=useState<ResourceLink|null|undefined>(undefined);const[deleting,setDeleting]=useState<ResourceLink|null>(null);const canManage=(item:ResourceLink)=>item.owner_id===me.id||me.is_head_hr;return <><div className="page-title"><div><span className="eyebrow">База знаний</span><h1>Полезные ссылки</h1><p>Сервисы, инструкции, обучение и важные корпоративные ресурсы.</p></div>{me.is_hr&&<button className="button primary" onClick={()=>setEditing(null)}><Plus/>Добавить ссылку</button>}</div><section className="links-grid">{items.map((item)=><article className="link-card" key={item.id}><span className="link-symbol"><Link2/></span><div><h3>{item.title}</h3><p>{item.description||item.url}</p><a href={item.url} target="_blank" rel="noreferrer">Открыть ресурс <ExternalLink/></a></div><div className="row-actions">{canManage(item)&&<button className="icon-button" onClick={()=>setEditing(item)}><Pencil/></button>}<button className="icon-button danger" onClick={()=>setDeleting(item)}><Trash2/></button></div></article>)}{!items.length&&<div className="card material-empty"><EmptyState icon={<Link2/>} title="Ссылок пока нет" text="HR может добавить первый полезный ресурс."/></div>}</section>{editing!==undefined&&<LinkForm profiles={profiles} item={editing??undefined} onClose={()=>setEditing(undefined)} onSubmit={async(values,share)=>{if(editing)await onUpdate(editing,values,share);else await onCreate(values,share);setEditing(undefined)}}/>}{deleting&&<Modal title="Удалить ссылку?" subtitle={deleting.title} onClose={()=>setDeleting(null)}><div className="delete-choices"><button className="button secondary" onClick={()=>setDeleting(null)}>Отмена</button><button className="button secondary" onClick={()=>void onHide(deleting).then(()=>setDeleting(null))}>Только у себя</button>{canManage(deleting)&&<button className="button danger-button" onClick={()=>void onDelete(deleting).then(()=>setDeleting(null))}>У всех</button>}</div></Modal>}</>}

function LinkForm({profiles,item,onClose,onSubmit}:{profiles:Profile[];item?:ResourceLink;onClose:()=>void;onSubmit:(values:{title:string;url:string;description:string},share:ShareDraft)=>Promise<void>}){const[values,setValues]=useState({title:item?.title??'',url:item?.url??'https://',description:item?.description??''});const[share,setShare]=useState<ShareDraft>({access_scope:item?.access_scope??'office',department:item?.department??null,recipient_ids:item?.recipient_ids??[]});return <Modal title={item?'Изменить ссылку':'Новая полезная ссылка'} onClose={onClose} wide><form className="form-stack" onSubmit={(e)=>{e.preventDefault();void onSubmit(values,share)}}><label>Название<input value={values.title} onChange={(e)=>setValues({...values,title:e.target.value})} required/></label><label>Адрес<input type="url" value={values.url} onChange={(e)=>setValues({...values,url:e.target.value})} required/></label><label>Описание<textarea value={values.description} onChange={(e)=>setValues({...values,description:e.target.value})}/></label><AccessEditor profiles={profiles} value={share} onChange={setShare}/><div className="modal-actions"><button type="button" className="button secondary" onClick={onClose}>Отмена</button><button className="button primary">Сохранить</button></div></form></Modal>}
