import { useEffect, useState } from 'react'
import { ArrowRight, Eye, EyeOff, LockKeyhole, Sparkles, Users } from 'lucide-react'
import { listDemoAccounts } from '../lib/api'

type DemoAccount={login:string;demo_password:string;full_name:string;job_title:string;role_label:string}
export function LoginPage({onLogin,busy,error}:{onLogin:(login:string,password:string)=>Promise<void>;busy:boolean;error:string}){
  const[login,setLogin]=useState('');const[password,setPassword]=useState('');const[show,setShow]=useState(false);const[accounts,setAccounts]=useState<DemoAccount[]>([])
  useEffect(()=>{void listDemoAccounts().then((rows)=>setAccounts(rows as DemoAccount[])).catch(()=>setAccounts([]))},[])
  return <main className="login-page"><section className="login-story"><div className="product-mark"><span><Sparkles/></span><div><b>КОРУС</b><small>Пространство развития</small></div></div><div className="story-copy"><span className="story-label">Единое пространство сотрудника</span><h1>Развитие начинается<br/>с понятного маршрута.</h1><p>ИПР, встречи, обратная связь и общение с командой — в одном рабочем пространстве.</p><div className="story-features"><div><Users/><span><b>Вся команда рядом</b><small>Сотрудник, руководитель и HR работают вместе</small></span></div><div><LockKeyhole/><span><b>Управляемый доступ</b><small>Документы и данные видят только нужные люди</small></span></div></div></div><small className="story-footer">КОРУС Консалтинг</small></section><section className="login-form-side"><div className="login-column"><form className="login-card" onSubmit={(event)=>{event.preventDefault();void onLogin(login,password)}}><div><span className="eyebrow">Добро пожаловать</span><h2>Войдите в аккаунт</h2><p>Используйте корпоративные логин и пароль</p></div><label>Логин<input value={login} onChange={(event)=>setLogin(event.target.value)} autoComplete="username"/></label><label>Пароль<div className="password-field"><input type={show?'text':'password'} value={password} onChange={(event)=>setPassword(event.target.value)} autoComplete="current-password"/><button type="button" onClick={()=>setShow(!show)} aria-label="Показать пароль">{show?<EyeOff/>:<Eye/>}</button></div></label>{error&&<div className="form-error">{error}</div>}<button className="button primary login-button" disabled={busy}>{busy?'Входим…':<>Войти <ArrowRight/></>}</button></form><section className="demo-accounts"><div><span className="eyebrow">Тестовые аккаунты</span><h3>Выберите пользователя</h3><p>Нажмите на карточку — логин и пароль подставятся автоматически.</p></div><div className="demo-account-list">{accounts.map((account)=><button key={account.login} onClick={()=>{setLogin(account.login);setPassword(account.demo_password)}}><span className="demo-initials">{account.full_name.split(/\s+/).slice(0,2).map((part)=>part[0]).join('')}</span><span><strong>{account.full_name}</strong><small>{account.job_title||'КОРУС'} · {account.role_label}</small></span><ArrowRight/></button>)}</div>{!accounts.length&&<p className="login-note">Тестовые аккаунты появятся после подключения базы. Можно войти вручную.</p>}</section></div></section></main>
}
