import { useEffect, useState } from 'react'
import { ArrowRight, Eye, EyeOff, Moon, Sparkles, Sun } from 'lucide-react'
import { listDemoAccounts } from '../lib/api'

type DemoAccount={login:string;demo_password:string;full_name:string;job_title:string;role_label:string}
export function LoginPage({onLogin,busy,error,theme,onToggleTheme}:{onLogin:(login:string,password:string)=>Promise<void>;busy:boolean;error:string;theme:'light'|'dark';onToggleTheme:()=>void}){
  const[login,setLogin]=useState('');const[password,setPassword]=useState('');const[show,setShow]=useState(false);const[accounts,setAccounts]=useState<DemoAccount[]>([])
  useEffect(()=>{void listDemoAccounts().then((rows)=>setAccounts(rows as DemoAccount[])).catch(()=>setAccounts([]))},[])
  return <main className="login-page"><section className="login-shell"><button type="button" className="login-theme-toggle" onClick={onToggleTheme} title={theme==='light'?'Включить тёмную тему':'Включить светлую тему'} aria-label={theme==='light'?'Включить тёмную тему':'Включить светлую тему'}>{theme==='light'?<Moon/>:<Sun/>}</button><header className="login-brand"><span><Sparkles/></span><div><b>КОРУС</b><small>Пространство развития</small></div></header><div className="login-intro"><span className="eyebrow">Рабочее пространство сотрудника</span><h1>Вход в систему</h1><p>Введите корпоративные данные или выберите тестовый аккаунт.</p></div><form className="login-card" onSubmit={(event)=>{event.preventDefault();void onLogin(login,password)}}><label>Логин<input value={login} onChange={(event)=>setLogin(event.target.value)} autoComplete="username"/></label><label>Пароль<div className="password-field"><input type={show?'text':'password'} value={password} onChange={(event)=>setPassword(event.target.value)} autoComplete="current-password"/><button type="button" onClick={()=>setShow(!show)} aria-label="Показать пароль">{show?<EyeOff/>:<Eye/>}</button></div></label>{error&&<div className="form-error">{error}</div>}<button className="button primary login-button" disabled={busy}>{busy?'Входим…':<>Войти <ArrowRight/></>}</button></form><section className="demo-accounts"><div className="demo-accounts-heading"><span className="eyebrow">Тестовые аккаунты</span><h2>Выберите сотрудника</h2><p>Данные для входа подставятся автоматически.</p></div><div className="demo-account-list">{accounts.map((account)=><button type="button" key={account.login} onClick={()=>{setLogin(account.login);setPassword(account.demo_password)}}><span className="demo-initials">{account.full_name.split(/\s+/).slice(0,2).map((part)=>part[0]).join('')}</span><span><strong>{account.full_name}</strong><small>{account.job_title||'КОРУС'} · {account.role_label}</small></span><ArrowRight/></button>)}</div>{!accounts.length&&<p className="login-note">Тестовые аккаунты появятся после подключения базы. Можно войти вручную.</p>}</section><footer className="login-footer">КОРУС Консалтинг</footer></section></main>
}
