import { useState } from 'react'
import { BookOpen, Check, Plus, Trash2, X } from 'lucide-react'
import type { IprTask, Profile } from '../types'
import { Badge, EmptyState, Modal } from './UI'
import { SelectField } from './SelectField'

const sections=['Проектная деятельность','Пресейл','Маркетинг','Развитие навыков и компетенций','Сертификация вендоров','Развитие готовых решений']
export function IprView({employee,me,tasks,readOnly=false,onAdd,onDecide,onDelete,onComplete}:{employee:Profile;me:Profile;tasks:IprTask[];readOnly?:boolean;onAdd:(v:Pick<IprTask,'section'|'title'|'description'|'expected_result'>)=>Promise<void>;onDecide:(task:IprTask,status:'approved'|'rejected',reason?:string)=>Promise<void>;onDelete:(task:IprTask)=>Promise<void>;onComplete:(task:IprTask,completed:boolean)=>Promise<void>}){
  const[open,setOpen]=useState(false);const[reject,setReject]=useState<IprTask|null>(null)
  const own=employee.id===me.id;const canDecide=!readOnly&&employee.manager_id===me.id;const canAdd=!readOnly&&(own||employee.hr_id===me.id||employee.manager_id===me.id||me.is_head_hr)
  const approved=tasks.filter((t)=>t.status==='approved');const requests=tasks.filter((t)=>t.status!=='approved');const completed=approved.filter((task)=>task.is_completed).length;const progress=approved.length?Math.round(completed/approved.length*100):100
  return <section className="card ipr-card"><div className="section-head"><div><span className="eyebrow">Индивидуальный план развития</span><h2>ИПР · {employee.full_name}</h2><p>Сотрудник отмечает выполненное самостоятельно</p></div><div className="ipr-head-actions">{approved.length>0&&<div className="ipr-progress"><strong>{progress}%</strong><span><i style={{width:`${progress}%`}}/></span><small>{completed} из {approved.length} задач</small></div>}{canAdd&&<button className="button primary small" onClick={()=>setOpen(true)}><Plus/>{own?'Предложить задачу':'Добавить задачу в ИПР'}</button>}</div></div>
    {canDecide&&requests.filter((t)=>t.status==='pending').length>0&&<div className="approval-strip"><strong>На согласовании: {requests.filter((t)=>t.status==='pending').length}</strong><span>После одобрения задача автоматически появится в ИПР сотрудника.</span></div>}
    {approved.length===0?<EmptyState icon={<BookOpen/>} title="ИПР пока не заполнен" text={readOnly?'Задачи можно добавить в отдельном разделе «Мой ИПР».':'Сотрудник может предложить задачу, а руководитель — согласовать её.'}/>:<div className="ipr-sections">{sections.map((section)=>{const rows=approved.filter((t)=>t.section===section);if(!rows.length)return null;return <div className="ipr-section" key={section}><h3>{section}</h3>{rows.map((task)=><TaskCard key={task.id} task={task} own={own&&!readOnly} onComplete={onComplete}/>)}</div>})}</div>}
    {!readOnly&&requests.length>0&&<div className="requests"><h3>{canDecide?'Запросы сотрудника':'Мои предложения'}</h3>{requests.map((task)=><div className="request-row" key={task.id}><div><div className="request-title"><strong>{task.title}</strong><Badge tone={task.status==='pending'?'orange':'red'}>{task.status==='pending'?'На согласовании':'Отклонено'}</Badge></div><p>{task.description}</p>{task.rejection_reason&&<small>Причина: {task.rejection_reason}</small>}</div><div className="row-actions">{canDecide&&task.status==='pending'&&<><button className="icon-button success" title="Одобрить" onClick={()=>void onDecide(task,'approved')}><Check/></button><button className="icon-button danger" title="Отклонить" onClick={()=>setReject(task)}><X/></button></>}{own&&<button className="icon-button" title="Удалить" onClick={()=>void onDelete(task)}><Trash2/></button>}</div></div>)}</div>}
    {open&&<TaskForm direct={!own} onClose={()=>setOpen(false)} onSubmit={async(v)=>{await onAdd(v);setOpen(false)}}/>}
    {reject&&<RejectForm task={reject} onClose={()=>setReject(null)} onSubmit={async(reason)=>{await onDecide(reject,'rejected',reason);setReject(null)}}/>}
  </section>
}
function TaskCard({task,own,onComplete}:{task:IprTask;own:boolean;onComplete:(task:IprTask,completed:boolean)=>Promise<void>}){return <article className={`task-card ${task.is_completed?'completed':''}`}><div className="task-title-row"><h4>{task.title}</h4>{own?<label className="completion-check"><input type="checkbox" checked={task.is_completed} onChange={(event)=>void onComplete(task,event.target.checked)}/><span>{task.is_completed?'Выполнено':'Отметить выполненной'}</span></label>:task.is_completed?<span className="task-status-complete">Выполнено</span>:null}</div><div className="task-columns"><div><span>Описание</span><p>{task.description||'—'}</p></div><div><span>Ожидаемый результат</span><p>{task.expected_result||'—'}</p></div></div></article>}
function TaskForm({direct,onClose,onSubmit}:{direct:boolean;onClose:()=>void;onSubmit:(v:Pick<IprTask,'section'|'title'|'description'|'expected_result'>)=>Promise<void>}){const[form,setForm]=useState({section:sections[0],title:'',description:'',expected_result:''});return <Modal title={direct?'Добавить задачу в ИПР':'Предложить задачу'} subtitle={direct?'Задача сразу появится в плане сотрудника.':'Она появится в ИПР после одобрения руководителя.'} onClose={onClose}><form className="form-stack" onSubmit={(e)=>{e.preventDefault();void onSubmit(form)}}><label>Раздел<SelectField value={form.section} options={sections.map((section)=>({value:section,label:section}))} onChange={(section)=>setForm({...form,section})} ariaLabel="Раздел ИПР"/></label><label>Название<input value={form.title} onChange={(e)=>setForm({...form,title:e.target.value})} required/></label><label>Описание<textarea value={form.description} onChange={(e)=>setForm({...form,description:e.target.value})}/></label><label>Ожидаемый результат<textarea value={form.expected_result} onChange={(e)=>setForm({...form,expected_result:e.target.value})}/></label><div className="modal-actions"><button type="button" className="button secondary" onClick={onClose}>Отмена</button><button className="button primary">{direct?'Добавить в ИПР':'Отправить'}</button></div></form></Modal>}
function RejectForm({task,onClose,onSubmit}:{task:IprTask;onClose:()=>void;onSubmit:(reason:string)=>Promise<void>}){const[reason,setReason]=useState('');return <Modal title="Отклонить задачу" subtitle={task.title} onClose={onClose}><form className="form-stack" onSubmit={(e)=>{e.preventDefault();void onSubmit(reason)}}><label>Причина<textarea value={reason} onChange={(e)=>setReason(e.target.value)} placeholder="Сотрудник увидит этот комментарий" required/></label><button className="button danger-button">Отклонить</button></form></Modal>}
